# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-anatomy.html

AWSTemplateFormatVersion: 2010-09-09
Description: >
  Deploys simple dynamodb table

Parameters: {}

Resources:
  KanbanTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: task09-kanban
      AttributeDefinitions:
        - AttributeName: 'TaskId'
          AttributeType: 'S'
        - AttributeName: 'Status'
          AttributeType: 'S'
        - AttributeName: 'SK'
          AttributeType: 'S'
        - AttributeName: 'GSI1-PK'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'TaskId'
          KeyType: 'HASH'
        - AttributeName: 'SK'
          KeyType: 'RANGE'
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: 'GSI1-PK'
              KeyType: 'HASH'
            - AttributeName: 'Status'
              KeyType: 'RANGE'
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - CreatedAt
              - TaskId
          ProvisionedThroughput:
            ReadCapacityUnits: 2
            WriteCapacityUnits: 2
      LocalSecondaryIndexes: []
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

Outputs:
  Table:
    Value: !Ref KanbanTable
    Description: Logical name of the table
  TableArn:
    Value: !GetAtt KanbanTable.Arn
