# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-anatomy.html

AWSTemplateFormatVersion: 2010-09-09
Description: >
  Deploys simple dynamodb table

Parameters: {}

Resources:
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: task10-dynamo
      AttributeDefinitions:
        - AttributeName: 'PK'
          AttributeType: 'S'
        - AttributeName: 'SK'
          AttributeType: 'S'
        - AttributeName: 'LSI1SK'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'PK'
          KeyType: 'HASH'
        - AttributeName: 'SK'
          KeyType: 'RANGE'
      LocalSecondaryIndexes:
        - IndexName: LSI1
          KeySchema:
            - AttributeName: 'PK'
              KeyType: 'HASH'
            - AttributeName: 'LSI1SK'
              KeyType: 'RANGE'
          Projection:
            ProjectionType: ALL
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

Outputs:
  Table:
    Value: !Ref Table
    Description: Logical name of the table
  TableArn:
    Value: !GetAtt Table.Arn
