version: '3.8'

services:
    app:
        build:
            context: app
        environment:
            APP_PORT: 9090
        ports:
            - '9090:9090'

    proxy:
        build:
            context: proxy
        environment:
            APP_HOST: app
            APP_PORT: 9090
            PROXY_PORT: 8080
        ports:
            - '8080:8080'
